services:

  seadoc:
    image: seafileltd/sdoc-server:1.0-latest
    container_name: seadoc
    volumes:
      - vsseadocdata:/shared
    # ports:
    #   - "80:80"
    environment:
      - DB_HOST=seafile-mariadb
      - DB_PORT=${SEAFILE_MYSQL_DB_PORT:-3306}
      - DB_USER=${SEAFILE_MYSQL_DB_USER:-seafile}
      - DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - DB_NAME=${SEADOC_MYSQL_DB_NAME:-seahub_db}
      - TIME_ZONE=${TIME_ZONE:-Etc/UTC}
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - NON_ROOT=${NON_ROOT:-false}
      - SEAHUB_SERVICE_URL=${SEAFILE_SERVER_PROTOCOL:-http}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
    depends_on:
      seafile-mariadb:
        condition: service_healthy
    networks:
      - seafile
      - revproxy

networks:
  seafile:
    external: true
  revproxy:
    external: true

volumes:
  vsseadocdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VSEADOCDATA_PATH}