services:
  baikal:
    image: ckulka/baikal:nginx
    restart: always
    ports:
      - 127.0.0.1:40102:80
    volumes:
      - config:/var/www/baikal/config
      - data:/var/www/baikal/Specific
    networks:
      - revproxy
      - baikal_network

  db:
    image: mariadb:11.3 # it could be mysql compatible db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - baikal_network
    environment:
      MARIADB_DATABASE: ${BAIKAL_DB_NAME}
      MARIADB_USER: ${BAIKAL_DB_USER}
      MARIADB_PASSWORD: ${BAIKAL_DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${BAIKAL_DB_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
      - db_conf:/etc/mysql

volumes:
  config:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BAIKAL_DATA_PATH}/config
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BAIKAL_DATA_PATH}/Specific
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${BAIKAL_DATA_PATH}/db
  db_conf:

networks:
  revproxy:
    external: true
  baikal_network:
    external: true