services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: always
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - nginx_vlog:/var/log/nginx:ro
      - vbandata:/data # Persist Fail2Ban data
      - vjail:/data/jail.d:ro
      - vaction:/data/action.d:ro
      - vfilter:/data/filter.d:ro
      - vlog:/var/log/fail2ban
    environment:
      F2B_IPTABLES_CHAIN: DOCKER-USER
      F2B_LOG_TARGET: /var/log/fail2ban/fail2ban.log
      TZ: $TZ

volumes:
  vbandata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VBAN_DATA_PATH}
  vjail:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VJAIL_PATH}
  vaction:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VACTION_PATH}
  vfilter:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VFILTER_PATH}
  vlog:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VLOG_PATH}
  nginx_vlog:
    name: nginx_vlog
    external: true