services:
  homebox:
    image: ghcr.io/sysadminsmedia/homebox:latest
#   image: ghcr.io/sysadminsmedia/homebox:latest-rootless
    container_name: homebox
    restart: always
    environment:
      - HBOX_LOG_LEVEL=info
      - HBOX_LOG_FORMAT=text
      - HBOX_WEB_MAX_FILE_UPLOAD=15
      # Please consider allowing analytics to help us improve Homebox (basic computer information, no personal data)
      - HBOX_OPTIONS_ALLOW_ANALYTICS=false
      - HBOX_OPTIONS_CURRENCY_CONFIG=/config/currency.cfg.json
      - HBOX_WEB_MAX_UPLOAD=100 # MB
      - HBOX_OPTIONS_ALLOW_REGISTRATION=false
      
      - HBOX_DATABASE_DRIVER=postgres
      - HBOX_DATABASE_HOST=homebox-postgres
      - HBOX_DATABASE_PORT=5432
      - HBOX_DATABASE_USERNAME=${POSTGRES_USER}
      - HBOX_DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - HBOX_DATABASE_DATABASE=${POSTGRES_DB}
      - HBOX_DATABASE_SSL_MODE=disable # for local db container it's acceptable

      - TZ=Europe/Moscow
    networks:
      - homebox
      - revproxy
    volumes:
      - vdata:/data/
      - ${CURRENCY_CFG_PATH}:/config/currency.cfg.json
    ports:
      - 127.0.0.1:${PORT}:7745
    depends_on:
      - homebox-postgres

  homebox-postgres:
    image: postgres:16-alpine
    container_name: homebox-postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Moscow
    networks:
        - homebox
    volumes:
        - pgdata:/var/lib/postgresql/data
    
networks:
  revproxy:
    external: true
  homebox:
    external: true

volumes:
  vdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_PATH}
  pgdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PGDATA_PATH}