services:
    postgres:
        image: postgres:16-alpine
        container_name: postgres
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
        # ports:
            # - 127.0.0.1:5432:5432
        restart: unless-stopped
        networks:
            - postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
    
    linkwarden:
        image: ghcr.io/linkwarden/linkwarden:latest
        container_name: linkwarden
        environment:
            - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            - NEXTAUTH_URL=${NEXTAUTH_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXT_PUBLIC_DISABLE_REGISTRATION=${IS_PUBLIC_AUTH_DISABLED}
        ports:
            - "${PORT}:3000"
        volumes:
            - data:/data/data
        restart: unless-stopped
        networks:
            - revproxy
            - postgres
        depends_on:
            - postgres

networks:
    revproxy:
        external: true
    postgres:
        external: true

volumes:
    pgdata:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VPGDATA}
    data:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: ${VDATA}