services:
    kopia:
        image: kopia/kopia:latest
        hostname: kopia
        container_name: kopia
        restart: unless-stopped
        networks:
          - revproxy
        environment:
            - KOPIA_PASSWORD=${KOPIA_REPOSITORY_PASSWORD}
            - RCLONE_CONFIG_PASS=${RCLONE_CONFIG_PASS}
            - TZ=Europe/Moscow
        volumes:
            # Mount local folders needed by kopia
            - vconfig:/app/config
            - vcache:/app/cache
            - vlog:/app/logs
            - ./data/export:/export # for export of backups
            - ./data/tmp:/tmp # for snapshot mounting
            - cert:/cert # tls certificate

            - ${RCLONE_CONFIG_PATH}:/app/rclone # for rclone config in rclone scenario (not for client repo)

            - ./config/docker-handle.sh:/docker-handle.sh:ro # script for stop/start containers
            - /var/run/docker.sock:/var/run/docker.sock:rw # docker unix socket to stop/start containers during snapshoting

            # baikal
            - baikal_config:/backup/baikal/config:ro
            - baikal_data:/backup/baikal/data:ro # Specific folder
            - baikal_db:/backup/baikal/db:ro # all data (stored in external db)

            # homebox
            - homebox_vdata:/backup/homebox/data:ro
            - homebox_pgdata:/backup/homebox/pgdata:ro

            # linkwarden
            - linkwarden_data:/backup/linkwarden/data:ro
            - linkwarden_pgdata:/backup/linkwarden/pgdata:ro

            # obsidian
            - self-hosted-livesync-server_data:/backup/obsidian/data:ro
            - /path/to/couchdb/self-hosted-livesync-server/data/local.ini:/backup/obsidian/local.ini:ro

            # paperless-ngx
            - paperless-ngx_data:/backup/paperless/data:ro
            - paperless-ngx_media:/backup/paperless/media:ro
            - paperless-ngx_pgdata:/backup/paperless/pgdata:ro

            # seafile data
            - seafile_vdata:/backup/seafile/data:ro
        command:
            - server
            - start
            - --grpc
            # - --tls-generate-cert ### on first run, activate it
            - --tls-cert-file=/cert/cert.pem
            - --tls-key-file=/cert/key.pem
            - --enable-actions
            - --address=0.0.0.0:${KOPIA_PORT}
            - --server-username=${KOPIA_USER}
            - --server-password=${KOPIA_USER_PASSWORD}

networks:
  revproxy:
    external: true

volumes:
  vconfig:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${VCONFIG}
  vcache:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: ${VCACHE}
  cert:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${CERT_PATH}
  vlog:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${VLOG_PATH}

  baikal_config:
    name: baikal_config
    external: true
  baikal_data:
    name: baikal_data
    external: true
  baikal_db:
    name: baikal_db
    external: true

  homebox_vdata:
    name: homebox_vdata
    external: true
  homebox_pgdata:
    name: homebox_pgdata
    external: true

  linkwarden_data:
    name: linkwarden_data
    external: true
  linkwarden_pgdata:
    name: linkwarden_data
    external: true

  paperless-ngx_data:
    name: paperless-ngx_data
    external: true
  paperless-ngx_media:
    name: paperless-ngx_media
    external: true
  paperless-ngx_pgdata:
    name: paperless-ngx_pgdata
    external: true
  
  seafile_vdata:
    name: seafile_vdata
    external: true

  self-hosted-livesync-server_data:
    name: self-hosted-livesync-server_data
    external: true
