version: "3.8"

    couchserver:
        image: couchdb:3.1.2
        ports:
            - "5984:5984"
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        volumes:
            # The files' owner will be id:5984 when you launch the image.
            # Because CouchDB writes on-the-fly configurations into local.ini.
            # So when you want to perform git pull or change something, you have to change owners back.
            - ./data:/opt/couchdb/data
            - ./config/local.ini:/opt/couchdb/etc/local.ini
        networks:
            - caddy
        labels:
            caddy: ${COUCHDB_HOST}
            # To avoid being crawled by Malicious Web Crawlers,
            # - Make index page to be forbidden.
            # - Set CouchDB into subdirectory
            caddy.handle_path: /*
            caddy.handle_path.0_respond: "\"\" 403"
            caddy.handle_path.0_header.-Server: ""
            caddy.handle_path_1: /${COUCHDB_URL_PATH}/*
            caddy.handle_path_1.0_reverse_proxy: "{{upstreams 5984}}"
        restart: always

networks:
  caddy:
    external: true