services:
    couchserver:
        image: couchdb:3.1.2
        container_name: obsidian-couchdb
        restart: always
        ports:
            - "127.0.0.1:40103:5984"
        environment:
            - COUCHDB_USER=${COUCHDB_USER}
            - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
        volumes:
            # The files' owner will be id:5984 when you launch the image.
            # Because CouchDB writes on-the-fly configurations into local.ini.
            # So when you want to perform git pull or change something, you have to change owners back.
            - ./data:/opt/couchdb/data
            - ./config/local.ini:/opt/couchdb/etc/local.ini
        networks:
            - revproxy
        
networks:
  revproxy:
    external: true